FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/CrudOperation-0.0.1-SNAPSHOT.jar CrudOperation-0.0.1-SNAPSHOT.jar
EXPOSE 8089
ENTRYPOINT ["java", "-jar", "CrudOperation-0.0.1-SNAPSHOT.jar"]
